export const SHOW_LOGIN_MODAL='SHOW_LOGIN_MODAL';
export const SET_USER_INFO='SET_USER_INFO';
export const LOGOUT='LOGOUT';
export const SET_LOGIN_SUCCESS_REDIRECTION_URL='SET_LOGIN_SUCCESS_REDIRECTION_URL';
export const SET_USER_SECREATE_KEY='SET_USER_SECREATE_KEY';
export const SET_GUEST_USER_SECREATE_KEY='SET_GUEST_USER_SECREATE_KEY';