export type TDoctor = {
    service_location_id: number,
    doctor_id: number,
    clinic: string,
    clinic_id: number,
    city: string,
    contact_no: string,
    location_lat: number,
    location_lng: number,
    service_charge: number,
    doctor_name: string,
    position: string,
    qualification_disp: string,
    experience: number,
    doctor_seo_url: string,
    gender: string,
    doctor_profile_pic: string,
    market_name: string,
    locality: string,
    state: string,
    specialists?: string,
    availability: string,
}
export type TWeeklyConsultingTiming = {
    sunday: number,
    sunday_1st_session_start: string,
    sunday_1st_session_end: string,
    sunday_2nd_session_start: string,
    sunday_2nd_session_end: string,
    monday: number,
    monday_1st_session_start: string,
    monday_1st_session_end: string,
    monday_2nd_session_start: string,
    monday_2nd_session_end: string,
    tuesday: number,
    tuesday_1st_session_start: string,
    tuesday_1st_session_end: string,
    tuesday_2nd_session_start: string,
    tuesday_2nd_session_end: string,
    wednesday: number,
    wednesday_1st_session_start: string,
    wednesday_1st_session_end: string,
    wednesday_2nd_session_start: string,
    wednesday_2nd_session_end: string,
    thursday: number,
    thursday_1st_session_start: string,
    thursday_1st_session_end: string,
    thursday_2nd_session_start: string,
    thursday_2nd_session_end: string,
    friday: number,
    friday_1st_session_start: string,
    friday_1st_session_end: string,
    friday_2nd_session_start: string,
    friday_2nd_session_end: string,
    saturday: number,
    saturday_1st_session_start: string,
    saturday_1st_session_end: string,
    saturday_2nd_session_start: string,
    saturday_2nd_session_end: string,
}
export type TSlnoGroup = {
    group_name: string,
    group_name_for_user: string,
    limit: number,
    booking_start: string,
    booking_complete_time: string,
    message: string
}
export type TSimilarDoctor = {
    service_location_id: number,
    doctor_id: number,
    clinic: string,
    clinic_id: number,
    contact_no: string,
    service_charge: string,
    place: string,
    location: string,
    doctor_name: string,
    position: string,
    doctor_seo_url: string,
    doctor_profile_pic: null | string,
    qualification_disp: string,
    experience: number,
    market_name: string,
    city: string,
    state: string,
    specialist_id: string,
    specialist_name: string,
}
export type TDoctorDetail = TWeeklyConsultingTiming & {
    id: number,
    doctor_id: number,
    clinic: string,
    clinic_id: number,
    service_charge: string,
    site_service_charge: string,
    availability: string,
    slno_type: string,
    consulting_time: string,
    doctor_name: string,
    profile_pic: string,
    short_name: null | string,
    gender: 'male' | 'female',
    experience: number,
    position: string,
    description: null | string,
    seo_url: string,
    registration_no: null | string,
    category: null | string,
    qualification_disp: string,
    specialization: null | string,
    clinic_name: string,
    clinic_mobile: string,
    clinic_city: string,
    clinic_location: string,
    clinic_locality: string,
    location_lat: number,
    location_lng: number,
    clinic_logo: null | string,
    clinic_seo_url: string,
    clinic_state: string,
    clinic_market: string,
    whatsapp_number: string,
    whatsapp_channel_link: string,
    clinic_dtlpg_url?: string,
    other_doc_cnt?: number,
    doctor_availability?: {
        date: string;
        first_session_start_time: string;
        first_session_end_time: string;
        second_session_start_time: string;
        second_session_end_time: string;
        service_loc_id: number;
    },
    settings: {
        payment_type: string,
        advance_booking_enable: number,
        emergency_booking_close: number,
        booking_close_message: string,
        book_by: 'app' | 'call' | 'manually',
        show_group_name_while_booking: number,
        raw_information: string,
        appointment_book_mode: string,
        allow_booking_request: number,
        slot_allocation_mode: string,
        mon_limit: number,
        mon_booking_start_time: string,
        tue_limit: number,
        tue_booking_start_time: string,
        wed_limit: number,
        wed_booking_start_time: string,
        thu_limit: number,
        thu_booking_start_time: string,
        fri_limit: number,
        fri_booking_start_time: string,
        sat_limit: number,
        sat_booking_start_time: string,
        sun_limit: number,
        sun_booking_start_time: string,
        enable_enquiry: number,
        show_patients_feedback: number,
        patient_info_required?: Array<{ label: string, key: string, type: string, value: string, display_to: "user" | "clinic_staff" | "all" }>
        display_consulting_timing?: null | Array<{ label: string, value: string[] }>,
        display_booking_timing?: null | Array<{ label: string, value: string[] }>,
        show_similar_business?: number
    }
    slno_groups?: Array<TSlnoGroup>,
    allSpecializations: {
        [group_category: string]: {
            name: string,
            icon: string,
            short_description: string, seo_url: string, group_category: string, seo_id: string
        }[]
    },
    business_type: string,
    partner_type: string,
    total_liked?: number,
    similar_doctors?: TSimilarDoctor[],
    treated_health_conditions?: Array<{
        condition: string,
        severity_levels: string[],
        no_of_cases: number | ""
    }>,
    treatments_available?: string[],
    seo_dt: {
        seo_url: string,
        short_seo_url: string
        title: string,
        description: string,
        h1: string,
        ldjson: string
    }
}
export type TDoctorvailableData = {
    available_date: string,
    available_on: string,
    first_session_start_time: string,
    first_session_end_time: string,
    second_session_start_time: string,
    second_session_end_time: string
}